package com.xorec.stunwire.model.db

enum class SessionMessageType {
    SESSION_MESSAGE_TYPE_DISCONNECT,
    SESSION_MESSAGE_TYPE_PEER_TYPING,
    SESSION_MESSAGE_TYPE_TEXT,
    SESSION_MESSAGE_TYPE_IMAGE,
    SESSION_MESSAGE_TYPE_READ,
    SESSION_MESSAGE_TYPE_DELETE
}