package com.example.stunwire.model.networking

enum class PlainMessageType {
    PLAIN_MESSAGE_TYPE_KEEP_ALIVE,
    PLAIN_MESSAGE_TYPE_WAITING_FOR_HANDSHAKE_DATA_STATE,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_DATA,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_DATA_APPROVED,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_COMPLETED,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_COMPLETED_RECEIVED,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_ERROR,
    PLAIN_MESSAGE_TYPE_HANDSHAKE_ERROR_RECEIVED
}