package com.example.stunwire.model.networking

enum class SessionStates {
    SESSION_STATE_NO_SETUP,
    SESSION_STATE_TYPE_SELECTION,
    SESSION_STATE_RETRIEVING_ADDRESS,
    SESSION_STATE_RETRIEVING_ADDRESS_ERROR,
    SESSION_STATE_ADDRESS_RETRIEVED,
    SESSION_STATE_PERFORMING_HANDSHAKE,
    SESSION_STATE_HANDSHAKE_ERROR,
    SESSION_STATE_SESSION_ACTIVE
}