package com.xorec.stunwire.model.networking

enum class EncryptedMessageType {
    MESSAGE_TYPE_CONTENT,
    MESSAGE_TYPE_END_OF_CONTENT_TRANSMISSION,
    MESSAGE_TYPE_RESEND_REQUEST,
    MESSAGE_TYPE_ALL_CONTENT_RECEIVED,
    MESSAGE_TYPE_RECEIVING_LIST,
    MESSAGE_TYPE_RECEIVING_LIST_FLUSH
}